" Random settings 
set visualbell
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set undodir=~/.vimundodir
set undofile

" Plugins
call plug#begin('$HOME/.dotfiles/.vim/plugged')

Plug 'mhinz/vim-startify' " Cool vim start screen
Plug 'joshdick/onedark.vim' " Onedark theme for vim
Plug 'sheerun/vim-polyglot' " Lots of language support for vim
Plug 'vimsence/vimsence' " Discord rich presence for vim
Plug 'tpope/vim-fugitive' " Git extensions for vim
Plug 'leafgarland/typescript-vim' " Typescript support
" Plug 'ycm-core/YouCompleteMe'

call plug#end()

" Some visuals
syntax on
colorscheme onedark
set number

" Quick shortcuts to edit an reload my vimrc
nnoremap <Leader>ve :e ~/.dotfiles/.vim/vimrc<CR>
" The above shortcut (\ve) opens my vimrc
nnoremap <Leader>vr :source ~/.dotfiles/.vim/vimrc<CR>
" and the other one (\vr) reloads my vimrc
